ALTER TYPE "CommerceEventType" ADD VALUE IF NOT EXISTS 'SHOP_IMPRESSION';
ALTER TYPE "CommerceEventType" ADD VALUE IF NOT EXISTS 'PRODUCT_IMPRESSION';
ALTER TYPE "CommerceEventType" ADD VALUE IF NOT EXISTS 'SHOWCASE_IMPRESSION';
